server:
  port: 8080

spring:
  application:
    name: soboon-soboon
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create   # 초기 개발에는 create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: INFO
    likelion.sajaboys.soboonsoboon.service.reco: DEBUG

app:
  test-user-id: ${TEST_USER_ID}

openai:
  api-key: ${OPENAI_API_KEY}
  chat-model: gpt-4o
  timeout-seconds: 8
  max-tokens: 600
