server:
  port: 8080

spring:
  application:
    name: soboon-soboon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create   # 초기 개발에는 create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework: INFO
